title: Flourish Oke
logo: /assets/img/timmy.png
#description: Experienced data scientist with 2 years experience in data science. Proficient in Python for data analysis, machine learning, and deep learning. Ensures data accuracy, adept in platform management. Excels in insights, drives decisions. Ready for impactful projects. Skilled in uncovering valuable insights in datasets, aiding businesses in making informed decisions. Dedicated to upholding data accuracy and integrity, with expertise in data platform management.
#show_downloads: true
theme: jekyll-theme-minimal
